# Generated by Django 3.1.6 on 2021-04-22 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_product_users_like'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='preferences',
            field=models.ManyToManyField(related_name='category_pref', to='shop.Category'),
        ),
    ]
