# Generated by Django 3.1.6 on 2021-05-12 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_preferences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferences',
            name='prefered_category',
            field=models.ManyToManyField(blank=True, related_name='prefered_category', to='shop.Category'),
        ),
    ]
